---

- name: Create LibGuides user account
  user:
    name: "{{ libguides_user }}"
    comment: "LibGuides Indexer Service Account"
    shell: "/bin/bash"
    home: "/home/{{ libguides_user }}"

- name: Create LibGuides Indexer Install Directory
  file:
    path: "{{ libguides_base_install_path }}"
    owner: "{{ libguides_user }}"
    group: "{{ libguides_user }}"
    mode: "0750"
    state: "directory"

- name: Install pipenv utility
  become_user: "{{ libguides_user }}"
  pip:
    name: "pipenv"
    executable: "{{ path_to_pip_exec }}"
    extra_args: "--user"